### PR TITLE
fix: change webpack dev server port to avoid websocket conflict

### PR DESCRIPTION
**Pull request by Einstellung**
Problem:
When running the demo prover-ts on macOS, encountered error:
"Invalid WebSocket frame: RSV1 must be clear"

Investigation:
- Several other macOS developers have reported this issue
- Found relevant discussions and similar cases
- You can find detailed discussions at: [websockets issues](https://github.com/websockets/ws/issues/2169)

Solution:
Based on the solutions shared in the [discussions](https://github.com/websockets/ws/issues/2169):
- Changed webpack-dev-server port from 8080 to 3000
- Successfully resolved the WebSocket connection issue

### CODE REVIEW

**Comment by heeckhau** [comment]
Hey @Einstellung, thanks for your PR!

I suspect there’s another process running on your computer that’s already serving HTTP data on port 8080. Your workaround of running the Prover demo on a different port is a great idea. However, port 3000 is also frequently used (e.g., for React applications). I suggest we choose a less commonly used default port instead, such as 3456. What do you think?

**Review by heeckhau — CHANGES_REQUESTED** [review]
Can you use a different port than `3000`?

**Comment by Einstellung** [comment]
Sorry, I previously shared the wrong link regarding my problem.

Here is the correct [link](https://github.com/websockets/ws/issues/2109)

As you can see, this is not a rare issue specific to my Mac, but rather a common problem that occasionally occurs on other Mac system as well.

I've already adjusted port to 3456, and it's now working fine on my Mac.

**Review by heeckhau — APPROVED** [review]
Thanks!

**Pull request merged**
